language: objective-c
before_install:
- gem install cocoapods -v '0.33.1'
- brew uninstall xctool; brew install xctool --HEAD;
xcode_workspace: VENSeparatorView.xcworkspace
xcode_scheme: VENSeparatorView
xcode_sdk: iphonesimulator